sudo: false
language: python
python:
  - "3.5"
install: "pip install -U tox"

env:
  matrix:
    - TESTENV=py27
    - TESTENV=py33
    - TESTENV=py34
    - TESTENV=py35
    - TESTENV=pypy

script: tox --recreate -e $TESTENV
